src/__tests__/greeter.test.ts

[こちらのチュートリアル](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html#running-your-typescript-web-app) を実装してみたにゃん

[Add] greeter.test.jsを実装

---

.circleci/config.yml

[Add] circleciの設定ファイルを追加する

---

src/1-basic-types/kittaka/day3/issue-1.test.ts
src/1-basic-types/kittaka/day3/issue-1.ts

[add] issue-1 の実装とテスト追加

---

src/3-interfaces/searchParamsStorage.test.ts

にゃーん
setterをやめて、一部分だけ更新するメソッドにしました。

2019-10-31 #2

---

src/1-basic-types/kitamura/boolean.test.ts
src/1-basic-types/kitamura/containSearchText.test.ts
src/1-basic-types/kitamura/getProgress.test.ts
src/3-interfaces/kitamura/handleStatusChange.test.ts
src/3-interfaces/kitamura/searchParamsStorage.test.ts
src/helloworld.test.ts

week 1のlintエラーを修正

---

src/1-basic-types/kittaka/day1/nyaaaan.ts
src/1-basic-types/kittaka/day2/issue-1.test.ts
src/1-basic-types/kittaka/day2/issue-1.ts
src/1-basic-types/kittaka/day2/issue-2.test.ts
src/1-basic-types/kittaka/day2/issue-2.ts
src/1-basic-types/kittaka/day3/issue-1.test.ts
src/1-basic-types/kittaka/day3/issue-1.ts
src/1-basic-types/kittaka/day4/issue-1.test.ts
src/1-basic-types/kittaka/day4/issue-1.ts

lint の気持ち
- カンマが嫌いらしい
- セミコロンが好きらしい
- メソッド間の改行は嫌いらしい
- クウォートはダブルクウォート派らしい

Lint 修正しました

---

src/1-basic-types/nishiyama/boolean.test.ts

[Add] isDog関数を実装してみた

---

src/4-classes/kitamura/animal.ts
src/4-classes/kitamura/cat.test.ts
src/4-classes/kitamura/cat.ts
src/4-classes/kitamura/nyan.ts

にゃんこクラスを実装しました

---

src/4-classes/kitamura/cat.test.ts
src/4-classes/kitamura/cat.ts
src/4-classes/kitamura/nyan.ts

にゃんこにおもちゃを渡すと、死ぬまで手放さない

---

src/4-classes/kitamura/abstractCat.ts
src/4-classes/kitamura/mikeCat.test.ts
src/4-classes/kitamura/mikeCat.ts
src/4-classes/kitamura/norweigianForestCat.test.ts
src/4-classes/kitamura/norweigianForestCat.ts
src/4-classes/kitamura/toy.ts

いろんなにゃんこを作ってみた

---

src/1-basic-types/scraperonce/play-with-function/Cat.ts
src/1-basic-types/scraperonce/play-with-function/GentlePerson.ts
src/1-basic-types/scraperonce/play-with-function/Mammal.ts
src/1-basic-types/scraperonce/play-with-function/Person.ts
src/1-basic-types/scraperonce/play-with-function/Toy.ts
src/1-basic-types/scraperonce/play-with-function/functions.test.ts
src/1-basic-types/scraperonce/play-with-function/functions.ts

ねこをbindして渡すようにしてみました
テストつくるの間に合わない・・・

ねこひとおもちゃをつくってみた

---

src/5-functions/kitamura/play.test.ts
src/5-functions/kitamura/play.ts

いろんな遊び方を実装しました

---

src/6-generics/kittaka/generics.test.ts
src/6-generics/kittaka/generics.ts

ジェネリクスのサンプル書いた

---

src/6-generics/kitamura/identity.test.ts
src/6-generics/kitamura/identity.ts
src/6-generics/kitamura/play.test.ts
src/6-generics/kitamura/play.ts

ジェネリクスを使った実装

---

src/1-basic-types/scraperonce/6-generics/CatBox.ts
src/1-basic-types/scraperonce/6-generics/ICat.ts
src/1-basic-types/scraperonce/6-generics/MaineCoon.ts
src/1-basic-types/scraperonce/6-generics/functions.test.ts
src/1-basic-types/scraperonce/6-generics/functions.ts

[Add] ねこボックスを作った

---

src/1-basic-types/scraperonce/6-generics/MyMap.test.ts
src/1-basic-types/scraperonce/6-generics/MyMap.ts

[Add] なかよし猫ずかんをつくりました

---

src/7-enums/scraperonce/Cat.test.ts
src/7-enums/scraperonce/Cat.ts
src/7-enums/scraperonce/enums.ts

[Add] 猫のきもちを考えてみました

---

src/7-enums/kitamura/CatFood.test.ts
src/7-enums/kitamura/CatFood.ts
src/7-enums/kitamura/CatHair.test.ts
src/7-enums/kitamura/CatHair.ts

enumで選択肢を作りました

---

src/7-enum/kitaka/number_enum/http_status.test.ts
src/7-enum/kitaka/number_enum/http_status.ts
src/7-enum/kitaka/string_enum/makurano.test.ts
src/7-enum/kitaka/string_enum/makurano.ts

[add] enums です

---

src/6-generics/kitamura/ImmutableMap.ts

Refactor immutable map

---

src/8-advanced-types/scraperonce/intersection-types/Bird.ts
src/8-advanced-types/scraperonce/intersection-types/Cat.ts
src/8-advanced-types/scraperonce/intersection-types/Fish.ts
src/8-advanced-types/scraperonce/intersection-types/FlyableCat.ts
src/8-advanced-types/scraperonce/intersection-types/IPet.ts
src/8-advanced-types/scraperonce/intersection-types/index.test.ts
src/8-advanced-types/scraperonce/intersection-types/index.ts

[Add] 飛べるねこさんを作った

---

src/9-util_types/kittaka/Startinglineup.ts

todolist です

---

src/8-advanced-types/kitamura/Surgery.test.ts

失敗したフニャンケンシュタイン

---

src/8-advanced-types/scraperonce/sugoi-types/types.test.ts
src/8-advanced-types/scraperonce/sugoi-types/types.ts

ややこしいのをやろうとした

---

src/9-util_types/nishiyama/extract-type.test.ts

[Fix] Extract の良さはまだ程遠い

---

src/8-advanced-types/kitamura/AvailableStatus.test.ts
src/8-advanced-types/kitamura/Surgery.test.ts

Omit and Extract

---

src/8-advanced-types/scraperonce/sugoi-types/types.test.ts

typeでMixinをしてみた

---

src/9-util_types/nishiyama/CatDic.test.ts
src/9-util_types/nishiyama/CatDic.ts

[Fix] Recordクラスを使って遊ぶ

---

src/9-util_types/kittaka/Actions.test.ts
src/9-util_types/kittaka/Adventurer.test.ts
src/9-util_types/kittaka/Adventurer.ts

ThisType 使ってみた 

---

README.md
src/9-symbols/kitamura/nyans.test.ts

symbolを使ってみた

---

src/1-basic-types/nishiyama/namespaces/Capability.test.ts
src/1-basic-types/nishiyama/namespaces/Capability.ts
src/1-basic-types/nishiyama/namespaces/Flyable.ts
src/1-basic-types/nishiyama/namespaces/Healable.ts
src/1-basic-types/nishiyama/namespaces/Speakable.ts
src/1-basic-types/nishiyama/namespaces/Swimmable.ts

[Add] namespaceを使ってみた

---

src/10-namespaces/kittaka/clients.test.ts
src/10-namespaces/kittaka/clients.ts

namespaces で区切った

---

src/1-basic-types/nishiyama/namespaces/Capability.test.ts
src/1-basic-types/nishiyama/namespaces/Capability.ts
src/1-basic-types/nishiyama/namespaces/Flyable.ts
src/1-basic-types/nishiyama/namespaces/Healable.ts
src/1-basic-types/nishiyama/namespaces/Speakable.ts
src/1-basic-types/nishiyama/namespaces/Swimmable.ts
src/10-namespaces/nishiyama/cats.ts

[Fix] namespaceを正しく使う

---

src/10-namespaces/scraperonce/Cats.ts
src/10-namespaces/scraperonce/main.test.ts
src/10-namespaces/scraperonce/main.ts

Namespaceをこまかくわけてマージされることを確認した（ねこで）

---

src/11-decorators/kittaka/cat.test.ts
src/11-decorators/kittaka/cat.ts

undefined Nyan

---

src/11-decorators/nishiyama/CatDecorator.test.ts

[Add] にゃんが言える子

---

src/11-decorators/kitamura/nyan.test.ts
src/11-decorators/kitamura/nyan.ts

にゃんをつけるにゃん

---

src/11-decorators/scraperonce/function.test.ts
src/11-decorators/scraperonce/function.ts

[Add] 関数デコレータでいぬとねこを分けてみた

---

src/11-decorators/kittaka/class_deco.test.ts
src/11-decorators/kittaka/class_deco.ts

爆発するタイプの猫です

---

src/11-decorators/nishiyama/SealedCat.test.ts
src/11-decorators/nishiyama/SealedCat.ts

[Add] クラスデコレータで常に最高キャットを作る

---

src/11-decorators/kitamura/Cat.test.ts
src/11-decorators/kitamura/Cat.ts

クラスニャンコレーター

---

src/11-decorators/scraperonce/DecoClass.test.ts
src/11-decorators/scraperonce/DecoClass.ts

クラスデコレータでしょうげきの事実

---

src/nishiyama/kopen/koupenchan.test.ts
src/nishiyama/kopen/koupenchan.ts
src/nishiyama/kopen/person.ts

[Add] コウペンちゃんを作る
